//! Origins:
//! - `testsuite/bsc.evaluator/prims/when/when.exp`
//! - `testsuite/bsc.bugs/bluespec_inc/b1424/b1424.exp`
//! - `testsuite/bsc.bugs/bluespec_inc/b1658/b1658.exp`
//! - `testsuite/bsc.bugs/bluespec_inc/b540/b540.exp`
//! - `testsuite/bsc.bsv_examples/SHA1/SHA1.exp`
//! - `testsuite/bsc.bsv_examples/SHA256/SHA2.exp`
//! - `testsuite/bsc.bsv_examples/SHA512/SHA2.exp`

use super::SimulationCase;

pub(super) const CASES: &[SimulationCase] = &[
    bluesim_case!(
        "bsc.evaluator/prims/when::When::bluesim",
        "testsuite/bsc.evaluator/prims/when",
        "When",
        "sysWhen.out.expected"
    ),
    icarus_case!(
        "bsc.evaluator/prims/when::When::icarus",
        "testsuite/bsc.evaluator/prims/when",
        "When",
        "sysWhen.out.expected"
    ),
    bluesim_case!(
        "bsc.bugs/bluespec_inc/b1424::InstOrder1::bluesim",
        "testsuite/bsc.bugs/bluespec_inc/b1424",
        "InstOrder1",
        "sysInstOrder1.out.expected"
    ),
    icarus_case!(
        "bsc.bugs/bluespec_inc/b1424::InstOrder1::icarus",
        "testsuite/bsc.bugs/bluespec_inc/b1424",
        "InstOrder1",
        "sysInstOrder1.out.expected"
    ),
    bluesim_case!(
        "bsc.bugs/bluespec_inc/b1424::InstOrder2::bluesim",
        "testsuite/bsc.bugs/bluespec_inc/b1424",
        "InstOrder2",
        "sysInstOrder2.out.expected"
    ),
    icarus_case!(
        "bsc.bugs/bluespec_inc/b1424::InstOrder2::icarus",
        "testsuite/bsc.bugs/bluespec_inc/b1424",
        "InstOrder2",
        "sysInstOrder2.out.expected"
    ),
    bluesim_case!(
        "bsc.bugs/bluespec_inc/b1424::FunctionLocation1::bluesim",
        "testsuite/bsc.bugs/bluespec_inc/b1424",
        "FunctionLocation1",
        "sysFunctionLocation1.out.expected"
    ),
    icarus_case!(
        "bsc.bugs/bluespec_inc/b1424::FunctionLocation1::icarus",
        "testsuite/bsc.bugs/bluespec_inc/b1424",
        "FunctionLocation1",
        "sysFunctionLocation1.out.expected"
    ),
    bluesim_case!(
        "bsc.bugs/bluespec_inc/b1424::FunctionLocation2::bluesim",
        "testsuite/bsc.bugs/bluespec_inc/b1424",
        "FunctionLocation2",
        "sysFunctionLocation2.out.expected"
    ),
    icarus_case!(
        "bsc.bugs/bluespec_inc/b1424::FunctionLocation2::icarus",
        "testsuite/bsc.bugs/bluespec_inc/b1424",
        "FunctionLocation2",
        "sysFunctionLocation2.out.expected"
    ),
    bluesim_case!(
        "bsc.bugs/bluespec_inc/b1424::ForLoop1::bluesim",
        "testsuite/bsc.bugs/bluespec_inc/b1424",
        "ForLoop1",
        "sysForLoop1.out.expected"
    ),
    icarus_case!(
        "bsc.bugs/bluespec_inc/b1424::ForLoop1::icarus",
        "testsuite/bsc.bugs/bluespec_inc/b1424",
        "ForLoop1",
        "sysForLoop1.out.expected"
    ),
    bluesim_case!(
        "bsc.bugs/bluespec_inc/b1424::RuleOrder1::bluesim",
        "testsuite/bsc.bugs/bluespec_inc/b1424",
        "RuleOrder1",
        "sysRuleOrder1.out.expected"
    ),
    icarus_case!(
        "bsc.bugs/bluespec_inc/b1424::RuleOrder1::icarus",
        "testsuite/bsc.bugs/bluespec_inc/b1424",
        "RuleOrder1",
        "sysRuleOrder1.out.expected"
    ),
    bluesim_case!(
        "bsc.bugs/bluespec_inc/b1424::RuleOrder2::bluesim",
        "testsuite/bsc.bugs/bluespec_inc/b1424",
        "RuleOrder2",
        "sysRuleOrder2.out.expected"
    ),
    icarus_case!(
        "bsc.bugs/bluespec_inc/b1424::RuleOrder2::icarus",
        "testsuite/bsc.bugs/bluespec_inc/b1424",
        "RuleOrder2",
        "sysRuleOrder2.out.expected"
    ),
    bluesim_case!(
        "bsc.bugs/bluespec_inc/b1424::RuleOrder3::bluesim",
        "testsuite/bsc.bugs/bluespec_inc/b1424",
        "RuleOrder3",
        "sysRuleOrder3.out.expected"
    ),
    icarus_case!(
        "bsc.bugs/bluespec_inc/b1424::RuleOrder3::icarus",
        "testsuite/bsc.bugs/bluespec_inc/b1424",
        "RuleOrder3",
        "sysRuleOrder3.out.expected"
    ),
    bluesim_case!(
        "bsc.bugs/bluespec_inc/b1424::RuleNameClash1::bluesim",
        "testsuite/bsc.bugs/bluespec_inc/b1424",
        "RuleNameClash1",
        "sysRuleNameClash1.out.expected"
    ),
    icarus_case!(
        "bsc.bugs/bluespec_inc/b1424::RuleNameClash1::icarus",
        "testsuite/bsc.bugs/bluespec_inc/b1424",
        "RuleNameClash1",
        "sysRuleNameClash1.out.expected"
    ),
    bluesim_case!(
        "bsc.bugs/bluespec_inc/b1424::RuleNameClash2::bluesim",
        "testsuite/bsc.bugs/bluespec_inc/b1424",
        "RuleNameClash2",
        "sysRuleNameClash2.out.expected"
    ),
    icarus_case!(
        "bsc.bugs/bluespec_inc/b1424::RuleNameClash2::icarus",
        "testsuite/bsc.bugs/bluespec_inc/b1424",
        "RuleNameClash2",
        "sysRuleNameClash2.out.expected"
    ),
    bluesim_case!(
        "bsc.bugs/bluespec_inc/b1424::MethodOrder1::bluesim",
        "testsuite/bsc.bugs/bluespec_inc/b1424",
        "MethodOrder1",
        "sysMethodOrder1.c.out.expected"
    ),
    icarus_case!(
        "bsc.bugs/bluespec_inc/b1424::MethodOrder1::icarus",
        "testsuite/bsc.bugs/bluespec_inc/b1424",
        "MethodOrder1",
        "sysMethodOrder1.v.out.expected"
    ),
    bluesim_case!(
        "bsc.bugs/bluespec_inc/b1424::MethodOrder2::bluesim",
        "testsuite/bsc.bugs/bluespec_inc/b1424",
        "MethodOrder2",
        "sysMethodOrder2.c.out.expected"
    ),
    icarus_case!(
        "bsc.bugs/bluespec_inc/b1424::MethodOrder2::icarus",
        "testsuite/bsc.bugs/bluespec_inc/b1424",
        "MethodOrder2",
        "sysMethodOrder2.v.out.expected"
    ),
    bluesim_case!(
        "bsc.bugs/bluespec_inc/b1424::MethodOrder3::bluesim",
        "testsuite/bsc.bugs/bluespec_inc/b1424",
        "MethodOrder3",
        "sysMethodOrder3.c.out.expected"
    ),
    icarus_case!(
        "bsc.bugs/bluespec_inc/b1424::MethodOrder3::icarus",
        "testsuite/bsc.bugs/bluespec_inc/b1424",
        "MethodOrder3",
        "sysMethodOrder3.v.out.expected"
    ),
    bluesim_case!(
        "bsc.bugs/bluespec_inc/b1658::MethodArg_ActionValue::bluesim",
        "testsuite/bsc.bugs/bluespec_inc/b1658",
        "MethodArg_ActionValue",
        "bug1658.out.expected"
    ),
    bluesim_case!(
        "bsc.bugs/bluespec_inc/b1658::MethodArg_Value::bluesim",
        "testsuite/bsc.bugs/bluespec_inc/b1658",
        "MethodArg_Value",
        "bug1658.out.expected"
    ),
    bluesim_case!(
        "bsc.bugs/bluespec_inc/b1658::ModulePort::bluesim",
        "testsuite/bsc.bugs/bluespec_inc/b1658",
        "ModulePort",
        "bug1658.out.expected"
    ),
    bluesim_case!(
        "bsc.bugs/bluespec_inc/b1658::ModuleParam::bluesim",
        "testsuite/bsc.bugs/bluespec_inc/b1658",
        "ModuleParam",
        "bug1658.out.expected"
    ),
    bluesim_case!(
        "bsc.bugs/bluespec_inc/b540::Bug540_1::bluesim",
        "testsuite/bsc.bugs/bluespec_inc/b540",
        "Bug540_1",
        "sysBug540_1.out.expected"
    ),
    icarus_case!(
        "bsc.bugs/bluespec_inc/b540::Bug540_1::icarus",
        "testsuite/bsc.bugs/bluespec_inc/b540",
        "Bug540_1",
        "sysBug540_1.out.expected"
    ),
    bluesim_case!(
        "bsc.bugs/bluespec_inc/b540::Bug540_2::bluesim",
        "testsuite/bsc.bugs/bluespec_inc/b540",
        "Bug540_2",
        "sysBug540_2.out.expected"
    ),
    icarus_case!(
        "bsc.bugs/bluespec_inc/b540::Bug540_2::icarus",
        "testsuite/bsc.bugs/bluespec_inc/b540",
        "Bug540_2",
        "sysBug540_2.out.expected"
    ),
    bluesim_case!(
        "bsc.bsv_examples/SHA1::KenSha1::bluesim",
        "testsuite/bsc.bsv_examples/SHA1",
        "KenSha1",
        "sysKenSha1.out.expected"
    ),
    icarus_case!(
        "bsc.bsv_examples/SHA1::KenSha1::icarus",
        "testsuite/bsc.bsv_examples/SHA1",
        "KenSha1",
        "sysKenSha1.out.expected"
    ),
    bluesim_case!(
        "bsc.bsv_examples/SHA256::KenSha2::bluesim",
        "testsuite/bsc.bsv_examples/SHA256",
        "KenSha2",
        "sysKenSha2.out.expected"
    ),
    icarus_case!(
        "bsc.bsv_examples/SHA256::KenSha2::icarus",
        "testsuite/bsc.bsv_examples/SHA256",
        "KenSha2",
        "sysKenSha2.out.expected"
    ),
    bluesim_case!(
        "bsc.bsv_examples/SHA512::KenSha2::bluesim",
        "testsuite/bsc.bsv_examples/SHA512",
        "KenSha2",
        "sysKenSha2.out.expected"
    ),
    icarus_case!(
        "bsc.bsv_examples/SHA512::KenSha2::icarus",
        "testsuite/bsc.bsv_examples/SHA512",
        "KenSha2",
        "sysKenSha2.out.expected"
    ),
];
